name: Waka Advanced

on:
  schedule:
    - cron: '0 5-21/2 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    # This block tells GitHub exactly what the robot is allowed to do
    permissions:
      contents: write
      user: read

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LINES_OF_CODE: "True"
