name: Waka Advanced

on:
  schedule:
    - cron: '0 5-21/2 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with
