name: Waka README

on:
  schedule:
    - cron: '0 5-21/2 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # ADD THIS LINE BELOW:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: "░▒▓█"
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
